# This app config can be used to operate against a local Docker for Desktop kubernetes cluster
logging:
  level:
    com.rackspace.salus.event: debug
salus.event:
  discovery:
    kubernetes-strategy:
      api-url: https://localhost:6443
      service-name: kapacitor
server:
  port: 0