salus:
  environment: local
spring:
  kafka:
    consumer:
      value-deserializer: com.rackspace.monplat.protocol.ExternalMetricDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: ${spring.application.name}-${salus.environment}
      auto-offset-reset: latest
  application:
    name: salus-event-engine-ingest
management:
  metrics:
    export:
      influx:
        uri: ${salus.metrics.influx.uri:http://localhost:8086}
        db: salus
        enabled: ${salus.metrics.influx.enabled:false}
    